# Generated by Django 5.2.8 on 2025-12-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_booked_at_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cinema',
            name='vip_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='showtime',
            name='vip_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
